name: Super-Linter with Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t K1rel/simple-web-server:latest

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push K1rel/simple-web-server:latest
